language: c

sudo: false

addons:
  apt:
    packages:
      - python-virtualenv
      - gfortran

install:
  - ./setup.sh
  - ./build.sh

script:
  - . env
  - . test.sh

after_success:
  - ./package.sh
  - ./pyenv/bin/python deploy.py

env:
  global:
    - prefix=local
    - srcpath=R-3.2.0
    - name=R
    - version=3.2.0
    - "url=http://lib.stat.cmu.edu/R/CRAN/src/base/R-3/R-3.2.0.tar.gz"
    - secure
